/*
 * TextSummarizerGUI.java
 *
 * Created on July 10, 2009, 11:21 PM
 */

package edu.research.textsummarization.gui;
import edu.research.textsummarization.util.*;

/**
 *
 * @author  Administrator
 */
public class TextSummarizerGUI extends javax.swing.JFrame 
{
    private String txt;
    private static TextSummarizerGUI gui_selfRef = null;
    private edu.research.textsummarization.controller.Controller c = null;
    private String final_summary;
    /** Creates new form TextSummarizerGUI */
    public TextSummarizerGUI() 
	{
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        browseButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Text Summarizer");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel2.setText("Input File (Original Text)");

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jLabel3.setText("Summarized Text");

        jButton1.setText("Summarize >>");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        browseButton.setText("Open File");
        browseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(32, 32, 32)
                .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 183, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 214, Short.MAX_VALUE)
                .add(jLabel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 103, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(100, 100, 100))
            .add(layout.createSequentialGroup()
                .add(21, 21, 21)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(browseButton)
                        .add(150, 150, 150)
                        .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 118, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 264, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jButton1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 216, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(25, 25, 25)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(42, 42, 42)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel2)
                            .add(jLabel3))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE))
                        .addContainerGap())
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jButton1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 39, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(138, 138, 138))))
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(browseButton)
                    .add(jLabel1))
                .addContainerGap(367, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void browseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseButtonActionPerformed
// TODO add your handling code here:
javax.swing.JFileChooser fc = new javax.swing.JFileChooser();
fc.setFileSelectionMode(0);
fc.setDialogTitle("Choose a file");
int returnVal = fc.showOpenDialog(this);
if (returnVal == javax.swing.JFileChooser.APPROVE_OPTION)
{
    try 
    {
        getURI(fc);
    } 
    catch (Exception exp)
    {
        System.out.println("something wrong");
    }    
}
}//GEN-LAST:event_browseButtonActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
    c = edu.research.textsummarization.controller.Controller.getInstance();
    /*new edu.research.textsummarization.controller.Controller();*/
    c.onSummarizeButtonClick(txt);
    final_summary = c.printSummary();
    jTextArea2.insert(final_summary, 0);
    //javax.swing.JScrollPane jsp1 = new javax.swing.JScrollPane(jTextArea2, javax.swing.JScrollPane.VERTICAL_SCROLLBAR_ALWAYS, javax.swing.JScrollPane.HORIZONTAL_SCROLLBAR_NEVER); 
    jTextArea2.setEditable(false);
    jTextArea2.setLineWrap(true);
    jTextArea2.setWrapStyleWord(true);
}//GEN-LAST:event_jButton1ActionPerformed
    public java.net.URI getURI(javax.swing.JFileChooser fc) throws Exception 
    {
      
    java.io.File f = fc.getSelectedFile();
    java.net.URI uri;
    System.out.println("URI =" + f.toURI().toString());
   // try
    //{
     uri = new java.net.URI(f.toURI().toString());
     //System.out.println("Path = " + uri.getPath());
     txt = FileUtil.getContentFromFile(uri);
     jTextArea1.insert(txt,0);
     jTextArea1.setEditable(false);
     jTextArea1.setLineWrap(true);
     jTextArea1.setWrapStyleWord(true);
        
     //System.out.println(txt);
    
    //}
    /*catch(Exception e)
    {
        System.out.println("something wrong");
    }*/
    
        
        return uri;  
    }
    public String getTxt()
    {
        return txt;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) 
	{
        java.awt.EventQueue.invokeLater(new Runnable()
		{
            public void run() 
			{
                new TextSummarizerGUI().setVisible(true);
            }
        });
    }
    
    public edu.research.textsummarization.controller.Controller getController()
    {
        return c;
    }
    public static TextSummarizerGUI getInstance()
    {
        if(gui_selfRef==null)
        {
            gui_selfRef = new TextSummarizerGUI();
        }
        return gui_selfRef;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton browseButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
    
}
